name: Update package version
on:
  repository_dispatch:
     types: [new-release]
  workflow_dispatch:
    inputs:
      name:
          description: 'Run?'
          required: true
          default: 'YES!'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Get versions
        run: |
          cat deb-framework/DEBIAN/control | grep Version | cut -d " " -f 2 > original.txt
          curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r ".tag_name" | cut -d "v" -f 2 > source.txt
      - name: var
        id: var
        run: |
          echo "original=$(cat deb-framework/DEBIAN/control | grep Version | cut -d " " -f 2)" >> "$GITHUB_OUTPUT"
          echo "source=$(curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r ".tag_name" | cut -d "v" -f 2)" >> "$GITHUB_OUTPUT"
      - name: Compare
        id: check
        run: echo "diff=$(if diff original.txt source.txt -q; then echo "false"; fi)" >> "$GITHUB_OUTPUT"
      - name: Patch it
        if: steps.check.outputs.diff != 'false'
        run: |
          cd deb-framework/DEBIAN
          sed -i 's/${{ steps.var.outputs.original }}/${{ steps.var.outputs.source }}/g' control

      - name: Push file
        if: steps.check.outputs.diff != 'false'
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          git add deb-framework/
          git commit --no-gpg-sign -m "new version released"
          git push
      
      - name: Push File
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}    

      - name: Repository Dispatch
        if: steps.check.outputs.diff != 'false'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          event-type: build