name: fetch source

on: 
    schedule:
    - cron:  '00 5 * * 1,3,5'
    workflow_dispatch:
       inputs:
        name:
            description: 'Run?'
            required: true
            default: 'YES!'
    pull_request:
    pull_request_target:    
    push:
permissions:                # Job-level permissions configuration starts here
        contents: write           # 'write' access to repository contents
        pull-requests: write
jobs:
    fetch-source:
       runs-on: ubuntu-latest
       steps:
      
        - uses: actions/checkout@v4
          with: 
            persist-credentials: false
            fetch-depth: 0
            token: ${{ secrets.PAT }}
        - name: Find latest aseprite version
          id: latest
          uses: oprypin/find-latest-tag@v1
          with:
            repository: aseprite/aseprite
            releases-only: true
            regex: 'v\d+.\d+.\d\d'
        
        - name: Git commit
          
          run: |
            echo "${{ steps.latest.outputs.tag }}" >> aseprite-versions/version.json
            
            git config user.email "92376650+MinhCreator@users.noreply.github.com"
            git config user.name "MinhCreator"
            git add aseprite-versions/
            git commit -m "new version released"
            git push 
        
        - name: Push File
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.PAT }}
            branch: ${{ github.ref }}
        
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.PAT }}
            event-type: new-release