name: fetch source

on: 
    push:
    workflow_dispatch:
        
       
permissions:                # Job-level permissions configuration starts here
        contents: write           # 'write' access to repository contents
        pull-requests: write
jobs:
    fetch-source:
        runs-on: ubuntu-latest
        
        steps:
        
            
            - name: Find latest aseprite version
              id: latest
              uses: oprypin/find-latest-tag@v1
              with:
                repository: aseprite/aseprite
                releases-only: true
                regex: 'v\d+.\d+.\d\d'
            
            - name: Checkout
              id: check
              uses: actions/checkout@v4
              with:
                repository: aseprite/aseprite
                ref: ${{ steps.latest.outputs.tag }}
                fetch-depth: 0

            - name: Generate version file
              run: echo "Aseprite-${{ steps.latest.outputs.tag }} fetched by github-actions" >./version.txt
            
                
            - run: mkdir -p ./artifact 
            - uses: actions/upload-artifact@v4
              with:
                name: version-file
                path: ./version.txt