name: RENEW
on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      name:
          description: 'Run?'
          required: true
          default: 'YES!'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      
      - name: Git commit
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          echo $(date +'%d-%m-%y') >> keep_active_repo
          git add .
          git commit -S -m "Keep active repo"
          git push