name: RENEW
on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      name:
          description: 'Run?'
          required: true
          default: 'YES!'
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Git commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo $(date +'%d-%m-%y') >> keep_active_repo
          git add .
          git commit --no-gpg-sign -m "Keep active repo"
          git push
      
      - name: Push File
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}