name: RENEW
on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      name:
          description: 'Run?'
          required: true
          default: 'YES!'

          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_committer_name: ${{ secrets.NAME }}
          git_committer_email: ${{ secrets.EMAIL }}
          gpg_private_key: ${{ secrets.WORK1 }}
        
      - name: Git commit
        run: |
          echo $(date +'%d-%m-%y') >> keep_active_repo
          git config --global user.signingkey E92D67CFBE34EF25
          git add .
          git commit -S -m "Keep active"
          git push